### PR TITLE
Add Teams PC Online/Offline state

### PR DESCRIPTION
**Pull request by Dielee**
Adding the PC status on which teams is running

### CODE REVIEW

**Comment by EBOOZ** [comment]
Hi, 

This looks like a specific change to meet your own expectations. Can you elaborate a bit more on what this will bring to people using the script/service?

Thanks!

**Comment by Dielee** [comment]
Good Morning, 

I use the PC status on the teams running to turn off the lights after shutting down the pc. Because the 'unavailable' status should not always turn off the light.

**Comment by EBOOZ** [comment]
I was having a look at the proposed changes, and by reading your comment again I was thinking: Unavailable state? I don't see that status in HA myself. When does this occur?

**Comment by EBOOZ** [comment]
I like the idea! Testing your solution at the moment.

What's the rationale behind the service not responding for 5 minutes? Could we lower that to 1 or 2 minutes for example?

**Comment by EBOOZ** [comment]
I've decided to implement this functionality slightly different, by using a binary_sensor for reporting if the service is online or offline so the status is leveraging HA language capabilities. 

Making sure the status changes in HA is done via setting the icon. As a result, displayed status always remains connected, instead of update -> connected.

Updates are part of commit https://github.com/EBOOZ/TeamsStatus/commit/76804579b5dc98e9daf52b2bfc80e0830226d5bc

**Pull request closed without merging**
