### PR TITLE
Improve performance / reduce CPU load and disk IO

### PR DESCRIPTION
**Pull request by andreasbrett**
Tail'ing the last 1000 lines twice every second results in unnecessary CPU load and disk I/O. I changed this to use the `-Wait` feature of `Get-Content`. Could shave down CPU usage from 3-4% to 0-1%.

First run will fetch the last 1000 lines of the Teams logfile and process them. After that Get-Content will monitor the file for changes and only report those to the subsequent Scriptblock.

### CODE REVIEW

**Comment by jimmyeao** [comment]
nice, running this and it works well

**Comment by vmax77** [comment]
This is really nice. I seem to get an error when I use the script from this commit. Any idea what I might be doing wrong? 

image

**Comment by andreasbrett** [comment]
> This is really nice. I seem to get an error when I use the script from this commit. Any idea what I might be doing wrong?
> 
> image

Sorry, I can't help here. I'm not using this script as a service as that is not permitted on my work laptop (for good reasons).

**Comment by felipecrs** [comment]
I'm using as a service and it's working for me just fine. I would advise to merge this, as it brings major benefits.

**Comment by vmax77** [comment]
I fixed it with changing the ENV var back to full path, and then it works

**Comment by chriscolden** [comment]
im using this as a service with the full path not env and its working great.

**Comment by AntoineGS** [comment]
Since this project seems abandoned I've created a copy here: https://github.com/AntoineGS/TeamsStatusV2
I have merged your PR in it already!

**Comment by EBOOZ** [comment]
I've updated the script to work with the current Teams client. Closing this one to clean up.

**Pull request closed without merging**
