### PR TITLE
Added webcam status capability

### PR DESCRIPTION
**Pull request by dcnoren**
Suggested PR which adds in webcam monitor capability if Teams is in a call, will check registry key to see if Teams is using the webcam. If it is, it will reflect "In a call - camera on". Otherwise, "In a call - camera off".

Likely needs testing and possibly a check on whether registry key is present or not to prevent errors.

### CODE REVIEW

**Comment by EBOOZ** [comment]
Nice find :) What is your use case to distinguish between camera on or off?

**Comment by dcnoren** [comment]
If camera is on, door status light is red. If camera is off but teams is busy/in a meeting, status light yellow. Otherwise, green.

Let's family come in when green and ask questions. Come in but don't make noise when yellow. Don't come in when red since they'll be on camera.

**Comment by EBOOZ** [comment]
If there's interest from others, I'm happy to add it to the master branch.

**Comment by woodshoes** [comment]
This would be great!  I'd use mine to turn my color coded light off (the one in the office) and turn it to white so I don't look red on camera :) 
Great work & a big THANK YOU - I use this ALL DAY!

**Comment by tuffelh** [comment]
Any idea when / if this will be merged?

**Comment by dcnoren** [comment]
> Any idea when / if this will be merged?

@tuffelh - not sure when @EBOOZ might decide to. Meanwhile, at least back from March, you could manually modify following these instructions: https://community.home-assistant.io/t/microsoft-teams-status/202388/61?u=dcnoren

**Comment by EBOOZ** [comment]
I'll investigate what's possible in https://github.com/EBOOZ/TeamsStatus/issues/51

**Pull request closed without merging**
